[package]
name = "git-jump"
version = "0.1.2"
edition = "2021"
description = "Quickly jump to any git repo on the system. Requires fzf and plocate."
license-file = "LICENSE.md"

[dependencies]
home = "0.5.9"
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
